name: Basic Workflow
on:
  workflow_dispatch:
    inputs:
       groups: 
          description: "groups"
          required: true
          default: "smoke"
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello all"
  
