name: Basic Workflow
on:
  workflow_dispatch:
    inputs:
       groups: 
          description: "groups"
          required: true
          default: "smoke"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world!"
  
