name: Basic Workflow
on:
  workflow_dispatch:
    inputs:
       groups: 
          description: "groups"
          required: true
          default: "smoke"
       xmlFiles:
          description: "xmlFiles"
          required: true
          default: "smokeGrid.xml"
          type: choice
          options:
            - smokeGrid.xml
            - smokeGridPcl.xml
          if: ${{ github.events.input.xmlFiles }} == "smokeGrid.xml"
              abc:
                 desciption:"abc"
                 required:"true"
                 default:"def"
jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - run: echo "Hello world!"
  
